core: Hydromt Core {
  catalog: Data Catalog {
    yaml
  }
  adapters: Data Adapters {
    RasterDataset
    Dataframe
    Geodataframe
    Geodataset
  }
  models: Model API {
    base: Base Model {
      grid: GridModel
      network: NetworkModel
      lumped: LumpedModel
      mesh: MeshModel
    }
  }
  catalog -> adapters: Constructs
  adapters -> models: Provides data to
}

plugins: Plugins {
  sfincs: Sfincs {
    text: |md
      Coastal hydrology
    |
  }
  wflow: Wflow {
    text: |md
      Cahcment hydrology
    |
  }
  fiat: FIAT {
    text: |md
      Flood impact assessment
    |
  }
  delwaq: Delwaq {
    text: |md
      water quality modeling      
    |
  }
}

user: {
  shape: person
}

providers: {
  aws: AWS
  gcs: GCS
  p-drive: P drive
}

configs: Model Configuration {
  yaml
  toml
  ini
}

user -> core.catalog: References
user -> configs: Writes

core.adapters <-> providers: Exchanges data with
core.models.base.grid -> plugins.sfincs
core.models.base -> plugins.wflow
core.models.base -> plugins.fiat
core.models.base -> plugins.delwaq

configs -> core.models: Builds
