shape: sequence_diagram
user: {
  shape: person
}
catalog

user -> catalog: references
user -> models: provides configuration
catalog -> adapters: constructs
adapters -> providers: request data
providers -> adapters: provide data
adapters -> models: builds
models -> user: provides model data
